### ISSUE TITLE
extreme fps drops in REI and recipe book when using a skyblock texture pack

### ISSUE THREAD

**Issue by alexytomi** [romangraef/Firmament#3] opened 2023-09-30 08:57 UTC
what am i supposed to put here lol heres the log and pics ig

used Fabulously Optimized Stable for 1.20.1 + some other mod

latest.log https://mclo.gs/He3WhYS
rei.log https://mclo.gs/sMbz3ES
rei-issues.log https://mclo.gs/5h5AxNr

![image](https://github.com/romangraef/Firmament/assets/60690056/e0e69197-bd2e-427d-9cb4-6c6afb1ccd56)

Here's my normal FPS with just the pack
![image](https://github.com/romangraef/Firmament/assets/60690056/9f99c62c-7626-4435-82b1-30989112ffb5)

**Comment by romangraef** [comment] 2023-09-30 11:21
I am almost certain this is caused by a bug in CIT Resewn (https://github.com/SHsuperCM/CITResewn/pull/315). The author of CIT Resewn sadly refuses to patch this into their version. You can either use my version (which i have in the discord), or try removing your pack (or moving that pack to use my version of custom textures). This will not resolve all your FPS problems (rendering a fuck ton of items *will* cause some FPS issues, although im looking into mitigating that with frame buffers, but thats an REI issue). For future reference, when talking about FPS/performance issues, please use a profiler like [spark](https://spark.lucko.me/).

**Comment by romangraef** [comment] 2023-10-01 16:59
Can you please provide a profile and feedback on whether or not CIT resewn is the problem? If not I will probably close the issue for missing information.

**Comment by romangraef** [comment] 2023-10-04 14:44
Closing as invalid, because of lack of information. Please reopen if the problem persists with the suggested fixes, and you can provide the information requested.

**Closed by romangraef** 2023-10-04 14:44 UTC
